spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/job_plateform
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Mehdimidou123!
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true